-- Add profile info columns to profiles table
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS full_name TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS phone TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS wallet_address TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS detailed_address TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bank_name TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS bank_account_number TEXT DEFAULT '';
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS order_count INTEGER DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS gender TEXT DEFAULT '';
